spring:

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: #*************************
            clientSecret: #**************************
            scope: email, public_profile
  data:
    rest:
      base-path: /data-api


  # datasource:
  #  url: jdbc:postgresql://{localhost:port}/caffeinedb
  #  username: postgres
  #  password: {postgres password}
  #  initialization-mode: always
  #  data: classpath:schema.sql
  # jpa:
  #  hibernate:
  #  ddl-auto: update


