server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope: email, public_profile
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/oauth2/jwks
          issuer-uri: http://authserver:9000

  artemis:
    host: artemis.caffeine.com
    port: 61617
    user: caffeine
    password: l3tm31n

  profiles:
    active: dev;

  # datasource:
  #  url: jdbc:postgresql://{localhost:port}/caffeinedb
  #  username: postgres
  #  password: {postgres password}
  #  initialization-mode: always
  #  data: classpath:schema.sql
  # jpa:
  #  hibernate:
  #   ddl-auto: update

  # data:
  #  rest:
  #   base-path: /data-api


